theme = "hook"

# The URL the site will be built for
base_url = "https://elvim.cc/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
    { name = "categories" },
    { name = "tags" },
]

[markdown]

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
# highlight_code = true (Old zola style)
[markdown.highlighting]
style = "inline"
theme = "github-dark"

[extra]
# Put all your custom variables here

links = [
    { title = "Mail", href = "mailto:elvime AT protonmail.com" },
]
